### ISSUE TITLE
https://www.nuget.org/packages?q=ManagedIrbis5

### ISSUE THREAD

**Issue by sevryukov** [amironov73/ManagedIrbis5#3]
Здравствуйте.

Возможно я что-то не так делаю или не разобрался в документации/версиях, но на NuGet не опубликован пакет с именем ManagedIrbis5: https://www.nuget.org/packages?q=ManagedIrbis5

Соответственно, при попытке выполнить команду `dotnet add package ManagedIrbis5` возникает ожидаемая ошибка:
`There are no versions available for the package 'ManagedIrbis5'`

**Comment by amironov73** [comment]
ManagedIrbis5 не опубликован на NuGet, т. к. API еще не стабилизирован.

**Comment by sevryukov** [comment]
В таком случае это противоречит заявленному в документации: https://managedirbis5.readthedocs.io/en/latest/chapter1.html#id2:~:text=%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F%D0%BC%D0%B8%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0%20%D0%98%D0%A0%D0%91%D0%98%D0%A164.-,%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0,%D1%81%20%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E%20%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%BE%D0%B9%20%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B%20dotnet%2C%20%D0%B2%D1%85%D0%BE%D0%B4%D1%8F%D1%89%D0%B5%D0%B9%20%D0%B2%20%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D1%83%20.NET%205%3A,-dotnet%20add%20package

Спасибо за уточнение.

**Comment by amironov73** [comment]
Виноват, документацию уберу от греха подальше.

Предварительные версии NuGet-пакетов можно скачать [отсюда](https://ci.appveyor.com/project/AlexeyMironov/managedirbis5/builds/47003276/artifacts) и подключить как локальный NuGet-репозиторий.

**Comment by sevryukov** [comment]
@amironov73 приношу свои извинения, но почему закрыт Issue? В NuGet не появился пакет и документация осталась без изменений. Ожидал, что Issue будет закрыт после какой-либо правки и закрытие можно использовать как повод вернуться к переходу на интеграцию с новым пакетом...

**Comment by amironov73** [comment]
В обозримой перспективе (в этом году - точно) не будет релиза ManagedIrbis5, а значит - не будет и релизного NuGet feed.
